src/main/java/kr/co/pinup/comments/Comment.java
src/main/java/kr/co/pinup/members/controller/MemberApiController.java
src/main/java/kr/co/pinup/postImages/PostImage.java
src/main/java/kr/co/pinup/postImages/model/dto/PostImageRequest.java
src/main/java/kr/co/pinup/postImages/service/PostImageService.java
src/main/java/kr/co/pinup/posts/Post.java
src/main/java/kr/co/pinup/posts/controller/PostApiController.java
src/main/java/kr/co/pinup/posts/controller/PostController.java
src/main/java/kr/co/pinup/posts/model/dto/CreatePostRequest.java
src/main/java/kr/co/pinup/posts/service/PostService.java
src/main/resources/static/js/comment.js
src/main/resources/static/js/post.js
src/main/resources/templates/index.html
src/main/resources/templates/layouts/support.html
src/main/resources/templates/views/posts/create.html
src/main/resources/templates/views/posts/detail.html
src/main/resources/templates/views/posts/list.html
src/main/resources/templates/views/posts/update.html
src/test/java/kr/co/pinup/config/S3ConfigTest.java
src/test/java/kr/co/pinup/members/MemberTest.java
src/test/java/kr/co/pinup/members/oauth/TestApiController.java
src/test/java/kr/co/pinup/posts/controller/CommentApiControllerTest.java
src/test/java/kr/co/pinup/posts/controller/PostApiControllerTest.java
src/test/java/kr/co/pinup/posts/controller/PostControllerTest.java
src/test/java/kr/co/pinup/posts/service/CommentServiceTest.java
src/test/java/kr/co/pinup/posts/service/PostImageServiceTest.java
src/test/java/kr/co/pinup/posts/service/PostServicelTest.java

feat: 게시판 생성/수정/삭제 및 댓글 생성/삭제 기능 구현을 위한 JS 파일 생성 및 레이아웃 파일에 JS 연동 및 테스트
- 게시판 생성, 수정, 삭제 기능 및 댓글 생성, 삭제 기능을 구현
- JS 파일을 생성하고, 이를 레이아웃 파일에 추가하여 동적 기능을 구현
- views와의 연동을 통해 게시판 및 댓글 관련 기능을 실시간으로 처리할 수 있도록 업데이트
- 게시판 및 댓글의 동적 생성/수정/삭제 기능을 통해 사용자 경험 향상
- 페이지 리로드 없이 실시간으로 변경 사항 반영
- `post.js`, `comment.js`에 동적 기능 추가
- 게시물 및 댓글에 대한 실시간 업데이트 기능 구현
- 레이아웃 파일에 JS 연동
- 게시판 및 댓글 생성/수정/삭제 기능을 확인
- 모든 동적 기능이 정상적으로 동작하는지 확인

feat: 게시판 생성/수정/삭제 및 댓글 생성/삭제 기능 구현을 위한 JS 파일 생성, 레이아웃 헤더에 추ê

---

src/main/java/kr/co/pinup/comments/Comment.java
src/main/java/kr/co/pinup/custom/customDialect/SecurityContextDialect.java
src/main/java/kr/co/pinup/faqs/Faq.java
src/main/java/kr/co/pinup/posts/Post.java
src/main/resources/templates/views/posts/create.html
src/test/java/kr/co/pinup/PinupApplicationTests.java
src/test/java/kr/co/pinup/config/S3ConfigTest.java
src/test/java/kr/co/pinup/faqs/FaqServiceTest.java
src/test/java/kr/co/pinup/faqs/controller/FaqApiControllerTest.java
src/test/java/kr/co/pinup/faqs/controller/FaqControllerTest.java
src/test/java/kr/co/pinup/members/controller/MemberControllerTest.java
src/test/java/kr/co/pinup/members/custom/MemberTestAnnotation.java
src/test/java/kr/co/pinup/members/oauth/GoogleClientTest.java
src/test/java/kr/co/pinup/members/oauth/GoogleOAuthTest.java
src/test/java/kr/co/pinup/members/oauth/NaverClientTest.java
src/test/java/kr/co/pinup/members/oauth/NaverOAuthTest.java
src/test/java/kr/co/pinup/members/oauth/OAuthTest.java
src/test/java/kr/co/pinup/members/oauth/TestApiController.java
src/test/java/kr/co/pinup/members/service/MemberServiceTest.java
src/test/java/kr/co/pinup/notices/controller/NoticeApiControllerTest.java
src/test/java/kr/co/pinup/notices/controller/NoticeControllerTest.java
src/test/java/kr/co/pinup/posts/controller/PostApiControllerTest.java
src/test/java/kr/co/pinup/posts/controller/PostControllerTest.java
src/test/java/kr/co/pinup/posts/service/PostImageServiceTest.java
src/test/java/kr/co/pinup/posts/service/PostServicelTest.java

- memberInfo -> @WithMockMember 전면 수정
- 전체 주석 처리 -> 배포 이후 수정 예정

Test 전면 수정

---

src/test/java/kr/co/pinup/posts/controller/PostApiControllerTest.java

- `testCreatePost` 테스트 메소드에서 `MultipartFile[]` 배열을 `MockMultipartFile`로 수정하여 2개의 이미지 파일을 전송하도록 수정하였습니다.
- `CreatePostRequest` 객체의 필드 값들이 올바르게 설정되었는지 확인했습니다.
- 인증된 사용자 정보를 `@WithMockMember` 어노테이션으로 추가하여, 인증 문제를 해결했습니다.
- 게시글 생성 API의 응답 상태 코드 `201 Created`와 함께, 생성된 게시글의 데이터를 검증하는 로직을 추가했습니다.
- 게시글 생성 API에 대한 단위 테스트가 정상적으로 작동하도록 수정하였으며, 파일 업로드와 인증 관련 문제를 해결하였습니다.
- 테스트가 예상한 결과와 정확히 일치하도록 하기 위한 수정입니다.
- `@WithMockMember`로 인증된 사용자로 요청을 보내 게시글 생성 요청을 시뮬레이션하고, 생성된 게시글의 응답 데이터를 검증했습니다.

Fix: 게시글 생성 단위 테스트 수정

---

src/main/resources/static/css/store_detail.css
src/main/resources/templates/views/stores/detail.html
src/main/resources/templates/views/stores/list.html

- `store` 등록 버튼을 `create` 에서 `list`로 이동

fix: 등록 버튼 이동

---

src/main/resources/templates/views/stores/detail.html
src/main/resources/templates/views/stores/list.html

chore: CSS 오류 및 list 오류 수정

---

src/main/resources/static/css/post_list.css
src/main/resources/static/css/post_modal.css
src/main/resources/static/js/post.js
src/main/resources/templates/views/posts/detail.html

**스타일 수정: 게시물 리스트 및 모달 반응형 개선**
- `px` 단위를 `vw`, `vh`로 변경하여 반응형 최적화
- 가독성을 높이기 위해 레이아웃 간격 조정
- 불필요한 스타일 정리 및 주석 추가
- 팝업 레이아웃에 `vw`, `vh` 단위 적용하여 웹 환경 최적화
- 본문 및 댓글 영역에 `vh` 단위 적용 및 길이 제한 추가
- 모달 스타일 변경 및 반응형 개선
- 댓글 작성 시 로그인 상태 확인 및 로그인 유도 추가
- 로그인하지 않은 사용자가 댓글을 작성하려 할 경우, 401 상태 코드를 확인하여 로그인 페이지로 리다이렉트
- 로그인 후 댓글을 작성할 수 있다는 알림 메시지 추가

스타일 수정: 게시물 리스트 및 모달 반응형 개선

---

src/main/java/kr/co/pinup/security/SecurityConstants.java
src/main/resources/static/css/header.css
src/main/resources/static/css/main.css
src/main/resources/static/js/header.js
src/main/resources/static/js/index.js
src/main/resources/static/js/member.js
src/main/resources/templates/fragments/header.html
src/main/resources/templates/index.html
src/main/resources/templates/layouts/layout.html
src/main/resources/templates/layouts/main.html
src/main/resources/templates/layouts/support.html
src/main/resources/templates/views/members/login.html
src/main/resources/templates/views/members/profile.html

- 로그인 후 닉네임이 길 경우 `...`으로 축약 표시  
- `store` 카드의 너비를 고정하여 크기 변동 방지  
- 스토어 리스트를 **5개만 표시**하도록 변경  
- **"더보기" 버튼 추가** → 클릭 시 `store` 페이지로 이동 가능  
- 스토어 리스트에 **위치 정보(location) 추가**  
- 햄버거 버튼 관련 기능을 `member.js`에서 `header.js`로 이동  
- `fetchStoreSummaries` 메서드를 `index.js`로 이동하여 **메인 화면에서 스토어 리스트 불러오는 기능 담당**  
- **Thymeleaf 속성** (예: `th:class`, `th:href`) 수정하여 동적 값을 제대로 처리할 수 있도록 개선

fix : main CSS 및 SecurityConstants

---

src/main/java/kr/co/pinup/store_operatingHour/OperatingHour.java
src/main/java/kr/co/pinup/store_operatingHour/model/dto/OperatingHourRequest.java
src/main/java/kr/co/pinup/store_operatingHour/model/dto/OperatingHourResponse.java
src/main/java/kr/co/pinup/store_operatingHour/repository/OperatingHourRepository.java
src/main/java/kr/co/pinup/stores/Store.java
src/main/java/kr/co/pinup/stores/model/dto/StoreRequest.java
src/main/java/kr/co/pinup/stores/model/dto/StoreResponse.java
src/main/java/kr/co/pinup/stores/model/dto/StoreUpdateRequest.java
src/main/java/kr/co/pinup/stores/service/StoreService.java
src/main/resources/static/css/store_create.css
src/main/resources/static/css/store_list.css
src/main/resources/static/js/store.js
src/main/resources/templates/layouts/layout.html
src/main/resources/templates/views/stores/create.html
src/main/resources/templates/views/stores/detail.html
src/main/resources/templates/views/stores/list.html

> ### 운영시간
> |  `OperatingHour` 를 통해 `Store` 운영시간을 관리하도록 변경
> - `OperatingHour`
>   - Entity 및 Request Response 추가
>   - store의 `create.html` 에 해당 항목 추가
>   - `store.js` 에 해당 항목 기능 추가
> ### 썸네일
> - 썸네일 선택 기능 추가
> ### CSS
> - `detail`
>   - 이미지 슬라이더가 자동으로 넘어가지 않도록 변경
> - `list`
>   - 이미지를 클릭시에도 해당 페이지로 이동하도록 변경
>   - 기타 CSS 세부 조정
> - `layout`
>   - `layout`에서 `pageStyle` 추가 및 해당 블록이 css 를 담당하도록 변경
>   - `head` 부분에 css를 넣기 위함

feat: Store 기능 추가

---

src/main/java/kr/co/pinup/config/SeoUtil.java
src/main/java/kr/co/pinup/config/SeoUtilConfig.java
src/main/resources/templates/layouts/layout.html

<html>
<body>
<h2 data-start="111" data-end="121" class="">PR 제목</h2>
<p data-start="122" data-end="165" class=""><code data-start="122" data-end="165">feat(seo): SeoUtil null 처리 및 템플릿 렌더 조건 개선</code></p>
<hr data-start="167" data-end="170" class="">
<h2 data-start="172" data-end="179" class="">개요</h2>
<p data-start="181" data-end="246" class="">SeoUtil 클래스 도입 이후, <code data-start="200" data-end="213">@WebMvcTest</code> 기반 테스트 환경에서 다음과 같은 오류들이 발생하였습니다:</p>
<ul data-start="248" data-end="375">
<li data-start="248" data-end="289" class="">
<p data-start="250" data-end="289" class=""><code data-start="250" data-end="270">HttpServletRequest</code>가 null로 평가되어 NPE 발생</p>
</li>
<li data-start="290" data-end="322" class="">
<p data-start="292" data-end="322" class="">SeoUtil Bean 미주입으로 인한 EL 평가 …

feat(seo): SeoUtil null 처리 및 템플릿 렌더 조건 개선

---

build.gradle
src/main/java/kr/co/pinup/stores/scheduler/StoreStatusScheduler.java
src/main/resources/static/js/location.js
src/main/resources/static/js/store.js
src/main/resources/templates/layouts/layout.html
src/main/resources/templates/views/stores/create.html
src/main/resources/templates/views/stores/detail.html
src/main/resources/templates/views/stores/list.html
src/main/resources/templates/views/stores/update.html

> - `layout` 에 난독화 된 js 추가
>   - 그에 따라 다른 html의 `pageScripts` 내부 js 삭제]
> - 필요없는 콘솔들 삭제
> - `store.js`의 필요없는 콘솔 삭제

chore: layout에 난독화 store, location 추가 및 기존 pageScripts 내부 script 삭제

---

src/main/java/kr/co/pinup/config/KakaoWebClientConfig.java
src/main/java/kr/co/pinup/util/SecretsFetcher.java
src/main/resources/static/css/store_detail.css
src/main/resources/static/js/store-detail.js
src/main/resources/templates/views/stores/detail.html

- `credentialsProvider` 추가로 인증 방식 변경
- 스토어 디테일에서 게시글 탭 들어갈 때 CSS 변경되지 않도록 조치
- 스토어 상세 페이지에서 포스트 동작하도록 변경
- `secretsFetcher`에 `credentialsProvider` 추가
- `store-detail.js`에서 이미지 함수의 변수명 변경
- `store-detail.css`에서 이미지 관련 태그 변경
- Close #이슈번호

Feat stores

---

src/main/java/kr/co/pinup/api/kakao/KakaoMapService.java
src/main/java/kr/co/pinup/comments/controller/CommentApiController.java
src/main/java/kr/co/pinup/exception/GlobalExceptionHandler.java
src/main/java/kr/co/pinup/faqs/Faq.java
src/main/java/kr/co/pinup/locations/model/dto/CreateLocationRequest.java
src/main/java/kr/co/pinup/security/filter/AccessTokenValidationFilter.java
src/main/java/kr/co/pinup/security/filter/SessionExpirationFilter.java
src/main/java/kr/co/pinup/stores/controller/StoreController.java
src/main/java/kr/co/pinup/util/SecretsFetcher.java
src/main/resources/templates/layouts/main.html
src/main/resources/templates/views/posts/detail.html
src/test/java/kr/co/pinup/comments/controller/CommentApiControllerDocsTest.java
src/test/java/kr/co/pinup/config/SecurityConfigTest.java
src/test/java/kr/co/pinup/members/custom/MyServiceWireMockTest.java
src/test/java/kr/co/pinup/stores/service/StoreServiceUnitTest.java

- store.js 호출 삭제
- 개발자 도구 오픈 시 /well-known/ 차단
- main layout : main, index store.js 수정
- security filter : AccessTokenFilter, SessionExpirationFilter에서 /well-known/ 차단 추가
- Close #이슈번호

fix : store js 전체 삭제 및 /.well-known/ 차단

---

.github/workflows/ci-cd.yml
README.md

actions에 github ip ssh 접근 허용 추가 및 완료후 제거
- actions에 github ip ssh 접근 허용 추가 및 완료후 제거
- Close #이슈번호

actions에 github ip ssh 접근 허용 추가 및 완료후 제거

---

.github/workflows/ci-cd.yml

actions에 aws configure 추가
- actions에 aws configure 추가
- Close #이슈번호

chore: actions aws configure 추가

---

.github/workflows/ci-cd.yml

actions에 aws configure 추가
- actions에 aws configure 추가
- Close #이슈번호

actions에 aws configure 추가

---

.github/workflows/ci-cd.yml

actions aws region secrets로 수정
- actions aws region secrets로 수정
- Close #이슈번호

actions aws region secrets로 수정

---

.github/workflows/ci-cd.yml

docker tag version 수정
- docker tag 지정한 version으로 사용하도록 수정
- Close #이슈번호

chore: docker tag version 수정

---

.github/workflows/ci-cd.yml

docker tag version 수정
- docker tag version 수정
- Close #이슈번호

docker tag version 수정

---

.github/workflows/ci-cd.yml

actions docker port 수정
- actions docker port 수정
- Close #이슈번호

chore: actions docker port 수정

---

src/main/java/kr/co/pinup/util/SecretsFetcher.java

application yml에 없을때 빈 문자로 가져오도록 수정
- application yml에 없을때 빈 문자로 가져오도록 수정
- Close #이슈번호

style: application yml에 없을때 빈 문자로 가져오도록 수정

---

.github/workflows/ci-cd.yml
src/main/java/kr/co/pinup/util/SecretsFetcher.java

application yml에 없을때 빈 문자로 가져오도록 수정
- application yml에 없을때 빈 문자로 가져오도록 수정
- Close #이슈번호

application yml에 없을때 빈 문자로 가져오도록 수정

---

src/main/java/kr/co/pinup/config/SecurityConfig.java
src/main/java/kr/co/pinup/exception/GlobalExceptionHandler.java
src/main/resources/static/css/post_modal.css
src/main/resources/static/js/post.js
src/main/resources/templates/views/posts/detail.html

운영환경에서 PATCH 요청 시 발생한 403 오류를 해결하기 위해 CORS 설정을 보완하고,  
게시글 작성 및 댓글 영역의 UX 개선과 인증 안정성 강화를 함께 반영한 PR입니다.
- Spring Security의 `CorsConfiguration`에 `"PATCH"` 및 `"OPTIONS"` 메서드를 추가
- 브라우저의 preflight 요청이 막히지 않도록 허용 메서드 확장
- 서버: `@Valid` 실패 시 어떤 필드가 잘못되었는지 상세 응답 (`GlobalExceptionHandler`)
- 프론트: `post.js`에서 사전 검증 및 유효성 메시지를 alert로 표시
- 댓글 입력창을 `.card-container` 내부로 이동하여 레이아웃 정리
- clamp 기반 높이 조정으로 다양한 화면 대응 (모바일~대형 모니터)
- overflow/scroll 관련 레이아웃 문제 해결
- 댓글 입력창 상단 불필요한 `hr` 제거 및 높이 확대
- 401 응답에 대해 먼저 분기 처리하여 JSON 파싱 오류 방지
- 로그인 유도 메시지 및 리다이렉트 흐름 안정화
- 서버 에러 메시지 전달 명확화
- 로컬 환경은 same-origin이기 때문에 CORS preflight 동작이 생략될 수 있습니다. 운영환경에서 실제 인증 흐름(PATCH 요청) 테스트 권장
- 비로그인 상태에서 게시글 작성 또는 댓글 작성 시, 401 응답 처리 및 알림 메시지가 정상 동작하는지 확인 필요
- 게시글 작성 실패 시 alert 메시지가 보이지 않으면 브라우저 콘솔 로그 확인 권장
- Close #이슈번호

feat(posts): 게시글 작성 유효성 검증 및 CORS 인증 문제 대응

---

build.gradle
src/main/java/kr/co/pinup/stores/Store.java
src/main/java/kr/co/pinup/stores/controller/StoreApiController.java
src/main/java/kr/co/pinup/stores/controller/StoreController.java
src/main/java/kr/co/pinup/stores/model/dto/StoreResponse.java
src/main/java/kr/co/pinup/stores/model/dto/StoreUpdateRequest.java
src/main/java/kr/co/pinup/stores/service/StoreService.java
src/main/resources/logback-spring.xml
src/main/resources/static/css/store-update.css
src/main/resources/static/css/store_detail.css
src/main/resources/static/js/store-detail.js
src/main/resources/static/js/store-update.js
src/main/resources/templates/views/stores/detail.html
src/main/resources/templates/views/stores/update.html

- 팝업 수정 페이지 빠진 코드로 인해 에러인 부분 추가
- logback 설정 파일 추가
- cloudwatch log 전송 의존성, aop 의존성 추가
- 팝업 수정 페이지 이동 에러
- 코드 누락 부분이 많아 에러 발생으로 유정 팀원이 push한 결과물로 추가
- logback-spring.xml 파일을 생성해 log 설정 추가
- 콘솔, 파일, cloudwatch에 전송에 대한 로그 설정
- cloudwatch에 log 전송하기 위한 클래스가 필요해 의존성 추가
- 로그 공통화 클래스에서 사용할 aop 의존성 미리 추가
- 코드 수정으로 인해 재배포 예정으로 패치버전 업데이트 v1.0.1
- Close #이슈번호

feat: 팝업 수정 페이지 빠진 코드 추가 & logback 설정 파일 추가

---

src/main/java/kr/co/pinup/security/filter/SessionExpirationFilter.java
src/main/java/kr/co/pinup/stores/Store.java
src/main/resources/logback-spring.xml
src/main/resources/static/js/member.js
src/main/resources/templates/error.html
src/main/resources/templates/fragments/footer.html

MDC를 활용한 logback 커스텀
SessionExpirationFilter가 모든 요청을 확인하기 때문에 해당 파일에 MDC 추가
- Close #이슈번호

logback MDC

---

src/main/java/kr/co/pinup/custom/logging/AppLogger.java
src/main/java/kr/co/pinup/custom/logging/AppLoggerImpl.java
src/main/java/kr/co/pinup/custom/logging/StructuredLogger.java
src/main/java/kr/co/pinup/custom/logging/model/dto/BaseLog.java
src/main/java/kr/co/pinup/custom/logging/model/dto/ErrorLog.java
src/main/java/kr/co/pinup/custom/logging/model/dto/InfoLog.java
src/main/java/kr/co/pinup/custom/logging/model/dto/WarnLog.java
src/main/java/kr/co/pinup/custom/mdc/MdcClassNameAspect.java
src/main/java/kr/co/pinup/custom/mdc/MdcLoggingFilter.java
src/main/java/kr/co/pinup/exception/GlobalExceptionHandler.java
src/test/java/kr/co/pinup/comments/controller/CommentApiControllerDocsTest.java
src/test/java/kr/co/pinup/comments/controller/CommentApiControllerSliceTest.java
src/test/java/kr/co/pinup/config/LoggerConfig.java
src/test/java/kr/co/pinup/faqs/controller/FaqApiControllerTest.java
src/test/java/kr/co/pinup/faqs/controller/FaqControllerTest.java
src/test/java/kr/co/pinup/members/controller/MemberApiControllerDocsTest.java
src/test/java/kr/co/pinup/members/controller/MemberApiControllerSliceTest.java
src/test/java/kr/co/pinup/members/controller/MemberControllerSliceTest.java
src/test/java/kr/co/pinup/notices/controller/NoticeApiControllerTest.java
src/test/java/kr/co/pinup/notices/controller/NoticeControllerTest.java
src/test/java/kr/co/pinup/posts/controller/PostApiControllerDocsTest.java
src/test/java/kr/co/pinup/posts/controller/PostApiControllerSliceTest.java
src/test/java/kr/co/pinup/posts/controller/PostControllerSliceTest.java

DTO 기반 구조화 로깅 시스템(AppLogger) 도입으로, 로그의 일관성, 가독성, 유지보수성을 향상시켰습니다. MDC를 활용해 컨텍스트 정보를 자동 삽입하고, 예외 상황은 GlobalExceptionHandler를 통해 통합 처리합니다.
- `AppLogger` 인터페이스 및 구현체(`AppLoggerImpl`, `StructuredLogger`) 추가
- `InfoLog`, `WarnLog`, `ErrorLog` 등 DTO 기반 로그 객체 정의 및 `BaseLog` 추상 클래스 구성
- `MdcLoggingFilter`, `MdcClassNameAspect` 추가로 요청/클래스 컨텍스트 자동 삽입
- `GlobalExceptionHandler`에서 `AppLogger`를 활용해 예외 상황 구조화 로깅 적용
- 테스트 전용 `LoggerConfig` 추가로 `AppLogger` 테스트 환경 구성
- `StructuredLogger`에 `ObjectMapper` 설정 추가 (`NON_NULL`) → 불필요한 `null` 필드 생략을 통해 로그 간결화 및 분석 효율성 향상
- 도메인별 테스트 클래스에 AppLogger 설정(@MockBean 또는 @Import) 추가하여 ApplicationContext 로딩 실패 해결
- 테스트 시 `AppLogger`는 `@TestConfiguration`을 통해 수동 주입 필요
- `ObjectMapper` 설정을 통해 `null` 필드를 JSON 직렬화에서 제외함으로써, 로그 구조의 불필요한 항목 제거 및 파싱 안정성 확보
- 예외 발생 시 …

feat: DTO 기반 구조화 로깅(AppLogger) 시스템 도입
